- main.go
*PS: specific address must be written later
tolong di merge ini ya. untuk cors allow origin
> Add CORS allow origin to handling request from frontend

- config/routes.go
- pkg/user/controller.go
- pkg/user/repository.go
- pkg/user/service.go
> add get all users to route

- pkg/user/model.go
- pkg/user/repository.go
- pkg/user/service.go
Change response for get users with struct responseUsers
> Tidy up get users

- config/routes.go
- pkg/auth/controller.go
- pkg/auth/model.go
- pkg/role/controller.go
- pkg/role/model.go
- pkg/role/repository.go
- pkg/role/service.go
- pkg/user/controller.go
- pkg/user/model.go
- pkg/user/repository.go
- pkg/user/service.go
- change role model
- change login response
- add api for soft delete user
> Add API for soft delete user

- pkg/user/controller.go
- pkg/user/repository.go
- pkg/user/service.go
- add total data
- modify query in case if user using keyword
route changes to:
localhost:3003/api/fo/users?keyword=john&limit=5&page=2
*assume we have 15 data's that included 'john', so with the endpoint above, the first data that would gonna show up onto the lists are the 6th data in the table from the 15 datas
***PLEASE TESTING BEFORE MERGE**
> Enhancement get users

- pkg/user/repository.go
fix bugs on activated and deactive user
> Tidy up fix bugs on active deactive user

- pkg/user/controller.go
- pkg/user/service.go
- utility/mailjet/mailjet.go
> Handling error response sendmail

- pkg/user/service.go
> Fix bugs update status when failed or resent email

- config/routes.go
- constant/errors.go
- pkg/grading/controller.go
- pkg/grading/model.go
- pkg/grading/service.go
According to payload on frontend, this endpoint was made
> Tidy up add new put save settings

- config/routes.go
- constant/errors.go
- helper/response.go
- pkg/gen-retail/controller.go
Check param settings has been set before check score
> Check param settings has been set before check score

- config/routes.go
- pkg/gen-retail/controller.go
> add download csv

- common/constant/errors.go
- config/migrations.go
- config/routes.go
- helper/response.go
- helper/string.go
- middleware/auth.go
- middleware/upload.go
- pkg/gen-retail/controller.go
- pkg/gen-retail/model.go
- pkg/gen-retail/repository.go
- pkg/gen-retail/service.go
> tidy up bulk search crud

- config/routes.go
> remove adminauth on get gradings endpoint

- pkg/gen-retail/model.go
- pkg/gen-retail/repository.go
- pkg/gen-retail/service.go
add pic member name to list bulk of admin tier
> add pic member name to list bulk admin tier

- middleware/auth.go
change status token failed 401 when expired or wrong token
> change status token failed 401 when expired or wrong token

- pkg/procat/livestatus/controller.go
- pkg/procat/livestatus/repository.go
- pkg/procat/livestatus/service.go
Rief, tolong merge ya....
ini ada tambahan dari gue di jobs detail,
dan juga tambah pagination di jobs head nya
> Add total jobsdetails

- pkg/procat/livestatus/controller.go
- pkg/procat/livestatus/repository.go
- pkg/procat/livestatus/service.go
Rief, minta tolong lg yak, merge ini.. buat total chart gue bedain sama total list jobs detail
> Add jobs total for chart

- pkg/procat/livestatus/model.go
- pkg/procat/livestatus/repository.go
Tolong merge ini ya bro, thank you
> Add column status to job head and update done

- pkg/procat/livestatus/controller.go
- pkg/procat/livestatus/repository.go
- pkg/procat/livestatus/service.go
> tidy-up-add-total-by-status

- pkg/procat/livestatus/controller.go
- pkg/procat/livestatus/init.go
- pkg/procat/livestatus/repository.go
- pkg/procat/livestatus/service.go
> add-feature-export-job-details

- app/config/env.go
- app/server/fiberserver.go
- pkg/core/auth/controller.go
- pkg/core/auth/init.go
> Change setting CORS to allowing Session Cookie to client's browser
